# Generated by Django 5.1.2 on 2024-10-23 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.timezone),
        ),
    ]
