# Generated by Django 5.1.2 on 2024-10-23 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_todoitem_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
